---
# Use a Python-based system in a 3.7 virtual environment.
# Per Travis docs, xenial must be used for Python 3.7 or newer.
dist: "xenial"
language: "python"
python:
  - "3.7"

# Need docker and docker-compose support.
services:
  - "docker"

before_install:
- docker ps -a

# Install required Python packages for testing and operation.
install:
 - "pip install pylint"

# Execute the linting and unit tests before spinning up containers.
# Once containers are up, print them out for logging purposes.
before_script:
  - "pylint HelloWorld/__init__.py"

script:
- docker image build . --tag hello-world:latest
- docker run -d --name app hello-world:latest
- docker exec app python -m unittest discover

after_script:
- docker rm -f app
